import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, extname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const contentRoot = join(root, "content");
const generatedFile = join(root, "generated", "cms-content.js");
const readJson = async (file) => JSON.parse(await readFile(file, "utf8"));
const byOrder = (a, b) => (Number(a.order) || 0) - (Number(b.order) || 0);

async function readCollection(name) {
  const entries = await readdir(join(contentRoot, name), { withFileTypes: true });
  const items = await Promise.all(entries.filter((entry) => entry.isFile() && extname(entry.name) === ".json").map((entry) => readJson(join(contentRoot, name, entry.name))));
  return items.sort(byOrder);
}

const legacySegments = (value) => {
  if (Array.isArray(value)) return value;
  const source = String(value || "");
  const result = [];
  const token = /(\*\*[^*]+\*\*|\[[^\]]+\]\([^\s)]+\))/g;
  let cursor = 0;
  for (const match of source.matchAll(token)) {
    if (match.index > cursor) result.push(source.slice(cursor, match.index));
    const item = match[0];
    if (item.startsWith("**")) result.push({ text: item.slice(2, -2), strong: true });
    else {
      const parts = /^\[([^\]]+)\]\(([^\s)]+)\)$/.exec(item);
      result.push({ text: parts[1].replace(/^\*\*|\*\*$/g, ""), href: parts[2], strong: /^\*\*/.test(parts[1]) });
    }
    cursor = match.index + item.length;
  }
  if (cursor < source.length) result.push(source.slice(cursor));
  return result;
};
const adaptResearch = (area) => ({
  ...area,
  description: (area.description || []).map(legacySegments),
  examples: (area.examples || []).map((example) => ({ ...example, body: (example.body || []).map(legacySegments), bullets: (example.bullets || []).map(legacySegments) }))
});
const adaptNews = (item) => ({ ...item, summary: legacySegments(item.summary), details: (item.details || []).map(legacySegments) });

const site = await readJson(join(contentRoot, "site.json"));
if (site.researchIntro?.body) site.researchIntro.body = site.researchIntro.body.map(legacySegments);
const research = (await readCollection("research")).map(adaptResearch);
const team = await readCollection("team");
const publicationItems = await readCollection("publications");
const publications = { publications: [], conferences: [], dataset: [] };
publicationItems.forEach((item) => { const category = publications[item.category] ? item.category : "publications"; const { category: _category, ...publication } = item; publications[category].push(publication); });
const news = (await readCollection("news")).map(adaptNews);
await mkdir(dirname(generatedFile), { recursive: true });
await writeFile(generatedFile, `/* Generated by tools/build-content.mjs. Do not edit directly. */\nwindow.CMS_CONTENT = ${JSON.stringify({ site, research, team, publications, news }, null, 2)};\n`, "utf8");
