import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, extname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const root = fileURLToPath(new URL("..", import.meta.url));
const contentRoot = join(root, "content");
const generatedFile = join(root, "generated", "cms-content.js");
const indexFile = join(root, "index.html");
const readJson = async (file) => JSON.parse((await readFile(file, "utf8")).replace(/^\uFEFF/, ""));
const byOrder = (a, b) => (Number(a.order) || 0) - (Number(b.order) || 0);

async function readCollection(name) {
  const entries = await readdir(join(contentRoot, name), { withFileTypes: true });
  const items = await Promise.all(entries.filter((entry) => entry.isFile() && extname(entry.name) === ".json").map((entry) => readJson(join(contentRoot, name, entry.name))));
  return items.sort(byOrder);
}

const legacySegments = (value) => {
  if (Array.isArray(value)) return value;
  const source = String(value || "");
  const result = [];
  const token = /(\*\*[^*]+\*\*|\[[^\]]+\]\([^\s)]+\))/g;
  let cursor = 0;
  for (const match of source.matchAll(token)) {
    if (match.index > cursor) result.push(source.slice(cursor, match.index));
    const item = match[0];
    if (item.startsWith("**")) result.push({ text: item.slice(2, -2), strong: true });
    else {
      const parts = /^\[([^\]]+)\]\(([^\s)]+)\)$/.exec(item);
      result.push({ text: parts[1].replace(/^\*\*|\*\*$/g, ""), href: parts[2], strong: /^\*\*/.test(parts[1]) });
    }
    cursor = match.index + item.length;
  }
  if (cursor < source.length) result.push(source.slice(cursor));
  return result;
};
const adaptResearch = (area) => ({
  ...area,
  description: (area.description || []).map(legacySegments),
  paragraphs: (area.paragraphs || []).map(legacySegments),
  challengeBullets: (area.challengeBullets || []).map(legacySegments),
  researchIntro: area.researchIntro ? legacySegments(area.researchIntro) : area.researchIntro,
  researchBullets: (area.researchBullets || []).map(legacySegments),
  closingText: area.closingText ? legacySegments(area.closingText) : area.closingText,
  sections: (area.sections || []).map((section) => ({ ...section, body: (section.body || []).map(legacySegments), bullets: (section.bullets || []).map(legacySegments) })),
  examples: (area.examples || []).map((example) => ({ ...example, body: (example.body || []).map(legacySegments), bullets: (example.bullets || []).map(legacySegments) }))
});
const adaptNews = (item) => ({ ...item, summary: legacySegments(item.summary), summaryParagraphs: item.summaryParagraphs ? item.summaryParagraphs.map(legacySegments) : undefined, details: (item.details || []).map(legacySegments) });

const escapeHtml = (value) => String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const safeHref = (value) => (/^(https?:\/\/|mailto:|#|\/)/i.test(String(value || "")) ? String(value) : "#");
const inlineHtml = (value) => legacySegments(value).map((part) => {
  if (typeof part === "string") return escapeHtml(part);
  const text = part.strong ? `<strong>${escapeHtml(part.text)}</strong>` : escapeHtml(part.text);
  return part.href ? `<a href="${escapeHtml(safeHref(part.href))}">${text}</a>` : text;
}).join("");
const plainText = (value) => legacySegments(value).map((part) => (typeof part === "string" ? part : part.text)).join("");

const site = await readJson(join(contentRoot, "site.json"));
const bio = await readJson(join(contentRoot, "bio.json"));
const teaching = await readJson(join(contentRoot, "teaching.json"));
const contact = await readJson(join(contentRoot, "contact.json"));
const hiddenDrawers = (await readCollection("hidden-drawers")).map(adaptResearch);
if (site.researchIntro?.body) site.researchIntro.body = site.researchIntro.body.map(legacySegments);
const research = (await readCollection("research")).map(adaptResearch);
const team = await readCollection("team");
const publicationItems = await readCollection("publications");
const publications = { publications: [], conferences: [], dataset: [] };
publicationItems.forEach((item) => { const category = publications[item.category] ? item.category : "publications"; const { category: _category, ...publication } = item; publications[category].push(publication); });
const news = (await readCollection("news")).map(adaptNews);
await mkdir(dirname(generatedFile), { recursive: true });
const generatedBody = JSON.stringify({ site, bio, teaching, contact, research, hiddenDrawers, team, publications, news }, null, 2);
await writeFile(generatedFile, `/* Generated by tools/build-content.mjs. Do not edit directly. */\nwindow.CMS_CONTENT = ${generatedBody};\n`, "utf8");

const contentHash = createHash("md5").update(generatedBody).digest("hex").slice(0, 10);
const indexHtml = await readFile(indexFile, "utf8");
let updatedIndexHtml = indexHtml.replace(/generated\/cms-content\.js\?v=[a-z0-9]+/i, `generated/cms-content.js?v=${contentHash}`);

// Crawlers and AI fetchers do not run the client-side renderer, so the deployed
// HTML gets a plain-text copy of the content. The browser scripts overwrite these
// containers before first paint, so this is invisible to real visitors.
const prerender = Boolean(process.env.NETLIFY || process.env.PRERENDER);

const teamGroups = [{ id: "current", label: "Current Members" }, { id: "alumni", label: "Alumni" }];
const staticTeam = () => teamGroups.map((group) => {
  const members = team.filter((member) => member.group === group.id);
  if (!members.length) return "";
  const cards = members.map((member) => [
    `<h3>${escapeHtml(member.name)}</h3>`,
    member.role ? `<p>${escapeHtml(member.role)}</p>` : "",
    (member.bullets || []).length ? `<ul>${member.bullets.map((item) => `<li>${inlineHtml(item)}</li>`).join("")}</ul>` : "",
    member.bio ? `<p>${inlineHtml(member.bio)}</p>` : "",
    (member.topics || []).length ? `<p>Topics: ${member.topics.map(escapeHtml).join(", ")}</p>` : "",
    (member.links || []).map((link) => `<a href="${escapeHtml(safeHref(link.href))}">${escapeHtml(link.label)}</a>`).join(" ")
  ].filter(Boolean).join("")).join("");
  return `<section><h2>${group.label}</h2>${cards}</section>`;
}).join("");

const publicationGroups = [["publications", "Publications"], ["conferences", "Conference Presentations"], ["dataset", "Dataset"]];
const staticPublications = () => publicationGroups.map(([key, label]) => {
  const items = publications[key] || [];
  if (!items.length) return "";
  const rows = items.map((item) => {
    const title = item.href ? `<a href="${escapeHtml(safeHref(item.href))}">${escapeHtml(item.title)}</a>` : escapeHtml(item.title);
    const meta = [item.authors, item.venue, item.year].filter(Boolean).map(escapeHtml).join(". ");
    return `<li>${title} ${meta}</li>`;
  }).join("");
  return `<section><h3>${label}</h3><ul>${rows}</ul></section>`;
}).join("");

const staticNews = () => news.map((item) => {
  const paragraphs = (item.summaryParagraphs && item.summaryParagraphs.length ? item.summaryParagraphs : [item.summary])
    .map((entry) => `<p>${inlineHtml(entry)}</p>`).join("");
  const details = (item.details || []).length
    ? `${item.detailsTitle ? `<h4>${escapeHtml(item.detailsTitle)}</h4>` : ""}<ul>${item.details.map((entry) => `<li>${inlineHtml(entry)}</li>`).join("")}</ul>`
    : "";
  return `<article><h3>${escapeHtml(item.dateLabel)}</h3>${paragraphs}${details}</article>`;
}).join("");

const injectInto = (html, attribute, inner) => {
  const pattern = new RegExp(`<(\\w+)([^>]*\\b${attribute}(?=[\\s>])[^>]*)>\\s*</\\1>`);
  const match = pattern.exec(html);
  if (!match) throw new Error(`Prerender target not found: ${attribute}`);
  return html.replace(pattern, `<${match[1]}${match[2]}>${inner}</${match[1]}>`);
};

if (prerender) {
  try {
    updatedIndexHtml = injectInto(updatedIndexHtml, "data-cms-bio-paragraphs", (bio.paragraphs || []).map((entry) => `<p>${inlineHtml(entry)}</p>`).join(""));
    updatedIndexHtml = injectInto(updatedIndexHtml, "data-cms-team", staticTeam());
    updatedIndexHtml = injectInto(updatedIndexHtml, "data-publication-list", staticPublications());
    updatedIndexHtml = injectInto(updatedIndexHtml, "data-news-archive", staticNews());
  } catch (error) {
    console.warn(`Prerender skipped: ${error.message}`);
    updatedIndexHtml = indexHtml.replace(/generated\/cms-content\.js\?v=[a-z0-9]+/i, `generated/cms-content.js?v=${contentHash}`);
  }

  const lines = [`# ${site.brand?.name || "Site"}`, "", site.hero?.text || "", ""];
  lines.push("## Publications", "");
  publicationGroups.forEach(([key, label]) => {
    const items = publications[key] || [];
    if (!items.length) return;
    lines.push(`### ${label}`, "");
    items.forEach((item) => lines.push(`- ${item.title} — ${[item.authors, item.venue, item.year].filter(Boolean).join(". ")}${item.href ? ` (${item.href})` : ""}`));
    lines.push("");
  });
  lines.push("## Team", "");
  teamGroups.forEach((group) => {
    const members = team.filter((member) => member.group === group.id);
    if (!members.length) return;
    lines.push(`### ${group.label}`, "");
    members.forEach((member) => {
      lines.push(`- ${member.name}${member.role ? ` — ${member.role}` : ""}`);
      (member.bullets || []).forEach((item) => lines.push(`  - ${plainText(item)}`));
      if (member.bio) lines.push(`  - ${plainText(member.bio)}`);
    });
    lines.push("");
  });
  lines.push("## News", "");
  news.forEach((item) => {
    lines.push(`### ${item.dateLabel}`, "");
    (item.summaryParagraphs && item.summaryParagraphs.length ? item.summaryParagraphs : [item.summary]).forEach((entry) => lines.push(plainText(entry)));
    (item.details || []).forEach((entry) => lines.push(`- ${plainText(entry)}`));
    lines.push("");
  });
  await writeFile(join(root, "llms.txt"), `${lines.join("\n").replace(/\n{3,}/g, "\n\n")}\n`, "utf8");
}

if (updatedIndexHtml !== indexHtml) await writeFile(indexFile, updatedIndexHtml, "utf8");
