import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, extname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const contentRoot = join(root, "content");
const generatedFile = join(root, "generated", "cms-content.js");

const readJson = async (file) => JSON.parse(await readFile(file, "utf8"));
const byOrder = (a, b) => (Number(a.order) || 0) - (Number(b.order) || 0);

async function readCollection(name) {
  const directory = join(contentRoot, name);
  const entries = await readdir(directory, { withFileTypes: true });
  const items = await Promise.all(entries
    .filter((entry) => entry.isFile() && extname(entry.name) === ".json")
    .map((entry) => readJson(join(directory, entry.name))));
  return items.sort(byOrder);
}

const site = await readJson(join(contentRoot, "site.json"));
const research = await readCollection("research");
const team = await readCollection("team");
const publicationItems = await readCollection("publications");
const publications = { publications: [], conferences: [], dataset: [] };
publicationItems.forEach((item) => {
  const category = publications[item.category] ? item.category : "publications";
  const { category: _category, ...publication } = item;
  publications[category].push(publication);
});
const news = await readCollection("news");

const payload = { site, research, team, publications, news };
await mkdir(dirname(generatedFile), { recursive: true });
await writeFile(
  generatedFile,
  `/* Generated by tools/build-content.mjs. Do not edit directly. */\nwindow.CMS_CONTENT = ${JSON.stringify(payload, null, 2)};\n`,
  "utf8"
);
